export class Tracksheet {
  public Track_Sheet_ID?: number;
  public Audit_ID: number;
  public Parameter_ID: number;
  public Area_ID: number;
  public Part_ID: number;
  public Checkpoint_ID: number;
  public Location_ID: number;
  public Specification_ID: number;
  public Image_ID: number;
  public Reading: string;
  public Remark: string;
  public Plant_ID: number;
  public Shop_ID: number;
  public Audit_Type_Id: number;
  public Is_Transfered?: boolean;
  public Is_Purgeable?: boolean;
  public Is_Edited?: boolean;
  public Is_Deleted?: boolean;
  public Inserted_Host?: string;
  public Inserted_User_ID?: number;
  public Inserted_Date?: Date;
  public Updated_Host?: string;
  public Updated_User_ID?: number;
  public Updated_Date?: Date;

  public Gap_PIST?: number;
  public Gap_Total_Check?: number;
  public Gap_Ok?: number;
  public Gap_Nok?: number;
  public Gap_NA?: number;
  public Flush_PIST?: number;
  public Flush_Total_Check?: number;
  public Flush_Ok?: number;
  public Flush_Nok?: number;
  public Flush_NA?: number;
  public Total_PIST?: number;
  public Plant_Code: any;
}
