//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_Audit_Plan_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MM_Audit_Plan_Master()
        {
            this.MM_Audit_Plan_Log_Details = new HashSet<MM_Audit_Plan_Log_Details>();
            this.MM_Vehicle_Audit = new HashSet<MM_Vehicle_Audit>();
        }
    
        public decimal Audit_Plan_ID { get; set; }
        public Nullable<decimal> Model_ID { get; set; }
        public Nullable<decimal> Shop_ID { get; set; }
        public Nullable<decimal> Schedule_Type_ID { get; set; }
        public Nullable<decimal> Assign_User_ID { get; set; }
        public Nullable<System.DateTime> Audit_Start_Date { get; set; }
        public Nullable<System.DateTime> Audit_End_Date { get; set; }
        public Nullable<bool> IS_Active { get; set; }
        public Nullable<decimal> SHIFT_NO { get; set; }
        public Nullable<decimal> Plant_ID { get; set; }
        public Nullable<decimal> Audit_Type_Id { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string Plant_Code { get; set; }
        public Nullable<bool> Is_Transfered { get; set; }
        public Nullable<decimal> Deleted_User_ID { get; set; }
        public Nullable<System.DateTime> Deleted_Date { get; set; }
        public Nullable<decimal> Frequency { get; set; }
    
        public virtual Audit_Type_Master Audit_Type_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_Audit_Plan_Log_Details> MM_Audit_Plan_Log_Details { get; set; }
        public virtual MM_Employee MM_Employee { get; set; }
        public virtual MM_Model MM_Model { get; set; }
        public virtual MM_Plant MM_Plant { get; set; }
        public virtual MM_Schedule_Type_Master MM_Schedule_Type_Master { get; set; }
        public virtual MM_Shop MM_Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_Vehicle_Audit> MM_Vehicle_Audit { get; set; }
    }
}
