//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_Audit_Plan_Log_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MM_Audit_Plan_Log_Details()
        {
            this.MM_Vehicle_Audit = new HashSet<MM_Vehicle_Audit>();
        }
    
        public decimal Audit_Plan_Log_ID { get; set; }
        public Nullable<decimal> Audit_Plan_ID { get; set; }
        public System.DateTime Audit_Due_Date { get; set; }
        public Nullable<int> Status { get; set; }
        public string StatusRemark { get; set; }
        public Nullable<decimal> Model_ID { get; set; }
        public Nullable<decimal> Shop_ID { get; set; }
        public Nullable<decimal> Plant_ID { get; set; }
        public Nullable<decimal> Audit_Type_Id { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string Plant_Code { get; set; }
        public Nullable<bool> Is_Transfered { get; set; }
        public Nullable<decimal> Deleted_User_ID { get; set; }
        public Nullable<System.DateTime> Deleted_Date { get; set; }
    
        public virtual MM_Audit_Plan_Master MM_Audit_Plan_Master { get; set; }
        public virtual MM_Plant MM_Plant { get; set; }
        public virtual MM_Shop MM_Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_Vehicle_Audit> MM_Vehicle_Audit { get; set; }
    }
}
