//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_Audit_BuildPhase_Mstr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MM_Audit_BuildPhase_Mstr()
        {
            this.MM_Vehicle_Audit = new HashSet<MM_Vehicle_Audit>();
        }
    
        public decimal Build_Phase_ID { get; set; }
        public string Build_Phase_Name { get; set; }
        public string Build_Phase_Description { get; set; }
        public decimal Plant_ID { get; set; }
        public Nullable<decimal> Shop_ID { get; set; }
        public Nullable<int> Line_ID { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<decimal> Audit_Type_Id { get; set; }
        public string Plant_Code { get; set; }
        public Nullable<bool> Is_Transferred { get; set; }
    
        public virtual Audit_Type_Master Audit_Type_Master { get; set; }
        public virtual MM_Plant MM_Plant { get; set; }
        public virtual MM_Shop MM_Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_Vehicle_Audit> MM_Vehicle_Audit { get; set; }
    }
}
