//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_Error_Log
    {
        public decimal EL_ID { get; set; }
        public Nullable<decimal> Plant_ID { get; set; }
        public Nullable<decimal> Shop_ID { get; set; }
        public Nullable<decimal> Line_ID { get; set; }
        public Nullable<decimal> BuyoffCode { get; set; }
        public string Controller_Name { get; set; }
        public string Action_Name { get; set; }
        public string Meta_Class_Name { get; set; }
        public string Method_Name { get; set; }
        public string Exception_Detail { get; set; }
        public string Inner_Exception { get; set; }
        public string Message { get; set; }
        public string Exception_Data { get; set; }
        public string Target_Site { get; set; }
        public string Stack_Trace { get; set; }
        public string Source { get; set; }
        public string H_Result { get; set; }
        public Nullable<bool> Is_Transferred { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public System.DateTime Inserted_Date { get; set; }
    }
}
