//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MM_Employee()
        {
            this.MM_Audit_Plan_Master = new HashSet<MM_Audit_Plan_Master>();
        }
    
        public decimal Employee_ID { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_Password { get; set; }
        public string Employee_No { get; set; }
        public string Email_Address { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<decimal> Country_Code { get; set; }
        public Nullable<decimal> Contact_No { get; set; }
        public Nullable<decimal> Role_ID { get; set; }
        public Nullable<bool> Gender { get; set; }
        public decimal Department_ID { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<decimal> Audit_Type_Id { get; set; }
        public Nullable<decimal> Plant_ID { get; set; }
        public Nullable<decimal> Shop_ID { get; set; }
        public Nullable<bool> Is_Transfered { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<bool> Is_AllShops { get; set; }
    
        public virtual Audit_Type_Master Audit_Type_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_Audit_Plan_Master> MM_Audit_Plan_Master { get; set; }
        public virtual MM_Department MM_Department { get; set; }
        public virtual MM_Plant MM_Plant { get; set; }
        public virtual MM_Shop MM_Shop { get; set; }
    }
}
