//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_FQ_Target_Master
    {
        public decimal FQ_Target_ID { get; set; }
        public Nullable<decimal> FY_Name { get; set; }
        public string FQ_Name { get; set; }
        public Nullable<decimal> FQ_Target_L3 { get; set; }
        public Nullable<decimal> FQ_Target_L4 { get; set; }
        public Nullable<decimal> Shop_ID { get; set; }
        public Nullable<decimal> Model_ID { get; set; }
        public Nullable<int> SORTORDER { get; set; }
        public Nullable<decimal> Plant_ID { get; set; }
        public Nullable<decimal> Audit_Type_Id { get; set; }
        public Nullable<bool> Is_Transferred { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string Plant_Code { get; set; }
    
        public virtual Audit_Type_Master Audit_Type_Master { get; set; }
        public virtual MM_Model MM_Model { get; set; }
        public virtual MM_Plant MM_Plant { get; set; }
        public virtual MM_Shop MM_Shop { get; set; }
    }
}
