//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_Image_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MM_Image_Master()
        {
            this.MM_Track_Sheet = new HashSet<MM_Track_Sheet>();
        }
    
        public decimal Image_ID { get; set; }
        public byte[] FileContent { get; set; }
        public string FileName { get; set; }
        public string ImageName { get; set; }
        public string FileType { get; set; }
        public string ContentType { get; set; }
        public decimal Shop_ID { get; set; }
        public decimal Model_ID { get; set; }
        public decimal Area_ID { get; set; }
        public decimal Part_ID { get; set; }
        public Nullable<decimal> Audit_Type_Id { get; set; }
        public decimal Plant_ID { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Transferred { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        public virtual Audit_Type_Master Audit_Type_Master { get; set; }
        public virtual MM_AreaMaster MM_AreaMaster { get; set; }
        public virtual MM_Model MM_Model { get; set; }
        public virtual MM_PartMaster MM_PartMaster { get; set; }
        public virtual MM_Plant MM_Plant { get; set; }
        public virtual MM_Shop MM_Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_Track_Sheet> MM_Track_Sheet { get; set; }
    }
}
