//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_Menus
    {
        public decimal Menu_ID { get; set; }
        public string LinkName { get; set; }
        public string ActionName { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<bool> Is_Transfered { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public string Documents_Name { get; set; }
        public string Technical_Name { get; set; }
        public int Sort_Order { get; set; }
        public Nullable<decimal> Audit_Type_Id { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    
        public virtual Audit_Type_Master Audit_Type_Master { get; set; }
    }
}
