//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_Plant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MM_Plant()
        {
            this.MM_AreaMaster = new HashSet<MM_AreaMaster>();
            this.MM_Audit_BuildPhase_Mstr = new HashSet<MM_Audit_BuildPhase_Mstr>();
            this.MM_Audit_Plan_Log_Details = new HashSet<MM_Audit_Plan_Log_Details>();
            this.MM_Audit_Plan_Master = new HashSet<MM_Audit_Plan_Master>();
            this.MM_CheckpointMaster = new HashSet<MM_CheckpointMaster>();
            this.MM_Employee = new HashSet<MM_Employee>();
            this.MM_FQ_Target_Master = new HashSet<MM_FQ_Target_Master>();
            this.MM_FY_Target_Master = new HashSet<MM_FY_Target_Master>();
            this.MM_Image_Master = new HashSet<MM_Image_Master>();
            this.MM_LocationMaster = new HashSet<MM_LocationMaster>();
            this.MM_Model = new HashSet<MM_Model>();
            this.MM_PartMaster = new HashSet<MM_PartMaster>();
            this.MM_Shift = new HashSet<MM_Shift>();
            this.MM_Shop = new HashSet<MM_Shop>();
            this.MM_Track_Sheet = new HashSet<MM_Track_Sheet>();
            this.MM_Vehicle_Audit = new HashSet<MM_Vehicle_Audit>();
        }
    
        public decimal Plant_ID { get; set; }
        public string Plant_Name { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public Nullable<bool> IS_Active { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string Sap_Code { get; set; }
        public string Plant_Code { get; set; }
        public Nullable<bool> Is_Transferred { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_AreaMaster> MM_AreaMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_Audit_BuildPhase_Mstr> MM_Audit_BuildPhase_Mstr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_Audit_Plan_Log_Details> MM_Audit_Plan_Log_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_Audit_Plan_Master> MM_Audit_Plan_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_CheckpointMaster> MM_CheckpointMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_Employee> MM_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_FQ_Target_Master> MM_FQ_Target_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_FY_Target_Master> MM_FY_Target_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_Image_Master> MM_Image_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_LocationMaster> MM_LocationMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_Model> MM_Model { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_PartMaster> MM_PartMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_Shift> MM_Shift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_Shop> MM_Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_Track_Sheet> MM_Track_Sheet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_Vehicle_Audit> MM_Vehicle_Audit { get; set; }
    }
}
