//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_Rights
    {
        public decimal Right_ID { get; set; }
        public string Right_Name { get; set; }
        public string Right_Description { get; set; }
        public Nullable<bool> Is_Transfered { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public decimal Inserted_User_ID { get; set; }
        public System.DateTime Inserted_Date { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<bool> Is_Show_Documentations { get; set; }
        public string Technical_Documentations { get; set; }
        public string Functional_Documentations { get; set; }
        public decimal Plant_ID { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public string Plant_Code { get; set; }
    }
}
