//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_Roles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MM_Roles()
        {
            this.MM_Menu_Role = new HashSet<MM_Menu_Role>();
            this.MM_User_Roles = new HashSet<MM_User_Roles>();
        }
    
        public decimal Role_ID { get; set; }
        public string Role_Name { get; set; }
        public string Role_Description { get; set; }
        public Nullable<bool> Is_Transfered { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public decimal Inserted_User_ID { get; set; }
        public System.DateTime Inserted_Date { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<bool> Is_Show_Documentations { get; set; }
        public string Technical_Documentations { get; set; }
        public string Functional_Documentations { get; set; }
        public decimal Plant_ID { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<decimal> Audit_Type_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_Menu_Role> MM_Menu_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_User_Roles> MM_User_Roles { get; set; }
    }
}
