//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_SpecificationMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MM_SpecificationMaster()
        {
            this.MM_Track_Sheet = new HashSet<MM_Track_Sheet>();
        }
    
        public decimal Specification_ID { get; set; }
        public string Specification_Name { get; set; }
        public string Specification_Desc { get; set; }
        public Nullable<decimal> Shop_ID { get; set; }
        public Nullable<decimal> Model_ID { get; set; }
        public Nullable<decimal> Area_ID { get; set; }
        public Nullable<decimal> Part_ID { get; set; }
        public Nullable<decimal> Checkpoint_ID { get; set; }
        public Nullable<decimal> Location_ID { get; set; }
        public Nullable<bool> Is_Gap { get; set; }
        public Nullable<bool> Is_Flushness { get; set; }
        public Nullable<decimal> MinVal { get; set; }
        public Nullable<decimal> MaxVal { get; set; }
        public Nullable<decimal> LCL { get; set; }
        public Nullable<decimal> UCL { get; set; }
        public Nullable<decimal> UCLR { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<int> SORTORDER { get; set; }
        public Nullable<decimal> Plant_ID { get; set; }
        public Nullable<decimal> Audit_Type_Id { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string Plant_Code { get; set; }
        public Nullable<bool> Is_Transferred { get; set; }
    
        public virtual MM_AreaMaster MM_AreaMaster { get; set; }
        public virtual MM_CheckpointMaster MM_CheckpointMaster { get; set; }
        public virtual MM_LocationMaster MM_LocationMaster { get; set; }
        public virtual MM_Model MM_Model { get; set; }
        public virtual MM_PartMaster MM_PartMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_Track_Sheet> MM_Track_Sheet { get; set; }
    }
}
