//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_Track_Sheet
    {
        public decimal Track_Sheet_ID { get; set; }
        public decimal Audit_ID { get; set; }
        public int Parameter_ID { get; set; }
        public decimal Area_ID { get; set; }
        public decimal Part_ID { get; set; }
        public decimal Checkpoint_ID { get; set; }
        public decimal Location_ID { get; set; }
        public decimal Specification_ID { get; set; }
        public Nullable<decimal> Image_ID { get; set; }
        public string Reading { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Is_NA { get; set; }
        public string Sap_Code { get; set; }
        public decimal Plant_ID { get; set; }
        public decimal Shop_ID { get; set; }
        public decimal Audit_Type_Id { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string Plant_Code { get; set; }
        public Nullable<bool> Is_Transferred { get; set; }
    
        public virtual Audit_Type_Master Audit_Type_Master { get; set; }
        public virtual MM_CheckpointMaster MM_CheckpointMaster { get; set; }
        public virtual MM_Gap_And_FlushMaster MM_Gap_And_FlushMaster { get; set; }
        public virtual MM_Image_Master MM_Image_Master { get; set; }
        public virtual MM_LocationMaster MM_LocationMaster { get; set; }
        public virtual MM_PartMaster MM_PartMaster { get; set; }
        public virtual MM_Plant MM_Plant { get; set; }
        public virtual MM_Shop MM_Shop { get; set; }
        public virtual MM_SpecificationMaster MM_SpecificationMaster { get; set; }
        public virtual MM_Vehicle_Audit MM_Vehicle_Audit { get; set; }
    }
}
