//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_User_Log
    {
        public decimal Row_ID { get; set; }
        public string Log_In_User { get; set; }
        public Nullable<System.DateTime> Log_In_Time { get; set; }
        public Nullable<System.DateTime> Log_out_Time { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public Nullable<bool> Log_In { get; set; }
    }
}
