//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_User_Activity_Logs
    {
        public decimal Log_ID { get; set; }
        public string User_Name { get; set; }
        public string User_Token_No { get; set; }
        public System.DateTime Logged_In_Time { get; set; }
        public string Audit_Type { get; set; }
        public string Shop_Name { get; set; }
        public string Plant_Code { get; set; }
    }
}
