//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_Vehicle_Audit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MM_Vehicle_Audit()
        {
            this.MM_Track_Sheet = new HashSet<MM_Track_Sheet>();
        }
    
        public decimal Audit_ID { get; set; }
        public Nullable<decimal> Audit_Plan_ID { get; set; }
        public Nullable<decimal> Audit_Plan_Log_ID { get; set; }
        public System.DateTime Audit_Date { get; set; }
        public string VIN_No { get; set; }
        public string Body_No { get; set; }
        public decimal Model_ID { get; set; }
        public string Model_Code { get; set; }
        public string Model_Name { get; set; }
        public string Variant_Name { get; set; }
        public string Color_Name { get; set; }
        public Nullable<decimal> Build_Phase_ID { get; set; }
        public Nullable<decimal> Auditor1_ID { get; set; }
        public Nullable<decimal> Auditor2_ID { get; set; }
        public Nullable<decimal> Shift_ID { get; set; }
        public Nullable<decimal> Gap_PIST { get; set; }
        public Nullable<decimal> Gap_Total_Check { get; set; }
        public Nullable<decimal> Gap_Ok { get; set; }
        public Nullable<decimal> Gap_Nok { get; set; }
        public Nullable<decimal> Gap_NA { get; set; }
        public Nullable<decimal> Flush_PIST { get; set; }
        public Nullable<decimal> Flush_Total_Check { get; set; }
        public Nullable<decimal> Flush_Ok { get; set; }
        public Nullable<decimal> Flush_Nok { get; set; }
        public Nullable<decimal> Flush_NA { get; set; }
        public Nullable<decimal> Total_PIST { get; set; }
        public decimal Plant_ID { get; set; }
        public decimal Audit_Type_Id { get; set; }
        public Nullable<decimal> Shop_ID { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Plant_Code { get; set; }
        public Nullable<bool> Is_Transferred { get; set; }
        public Nullable<bool> Is_Gapgun { get; set; }
    
        public virtual Audit_Type_Master Audit_Type_Master { get; set; }
        public virtual MM_Audit_BuildPhase_Mstr MM_Audit_BuildPhase_Mstr { get; set; }
        public virtual MM_Audit_Plan_Log_Details MM_Audit_Plan_Log_Details { get; set; }
        public virtual MM_Audit_Plan_Master MM_Audit_Plan_Master { get; set; }
        public virtual MM_Model MM_Model { get; set; }
        public virtual MM_Plant MM_Plant { get; set; }
        public virtual MM_Shift MM_Shift { get; set; }
        public virtual MM_Shop MM_Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_Track_Sheet> MM_Track_Sheet { get; set; }
    }
}
