//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OneD_DB_Entity : DbContext
    {
        public OneD_DB_Entity()
            : base("name=OneD_DB_Entity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Audit_Type_Master> Audit_Type_Master { get; set; }
        public virtual DbSet<MM_AreaMaster> MM_AreaMaster { get; set; }
        public virtual DbSet<MM_Audit_BuildPhase_Mstr> MM_Audit_BuildPhase_Mstr { get; set; }
        public virtual DbSet<MM_Audit_Plan_Log_Details> MM_Audit_Plan_Log_Details { get; set; }
        public virtual DbSet<MM_Audit_Plan_Log_Details_Deleted> MM_Audit_Plan_Log_Details_Deleted { get; set; }
        public virtual DbSet<MM_Audit_Plan_Master> MM_Audit_Plan_Master { get; set; }
        public virtual DbSet<MM_CheckpointMaster> MM_CheckpointMaster { get; set; }
        public virtual DbSet<MM_Department> MM_Department { get; set; }
        public virtual DbSet<MM_Documents_Master> MM_Documents_Master { get; set; }
        public virtual DbSet<MM_Employee> MM_Employee { get; set; }
        public virtual DbSet<MM_Error_Log> MM_Error_Log { get; set; }
        public virtual DbSet<MM_FQ_Target_Master> MM_FQ_Target_Master { get; set; }
        public virtual DbSet<MM_FY_Target_Master> MM_FY_Target_Master { get; set; }
        public virtual DbSet<MM_Gap_And_FlushMaster> MM_Gap_And_FlushMaster { get; set; }
        public virtual DbSet<MM_Image_Master> MM_Image_Master { get; set; }
        public virtual DbSet<MM_Location_Mapping> MM_Location_Mapping { get; set; }
        public virtual DbSet<MM_LocationMaster> MM_LocationMaster { get; set; }
        public virtual DbSet<MM_Menu_Role> MM_Menu_Role { get; set; }
        public virtual DbSet<MM_Menus> MM_Menus { get; set; }
        public virtual DbSet<MM_Model> MM_Model { get; set; }
        public virtual DbSet<MM_PartMaster> MM_PartMaster { get; set; }
        public virtual DbSet<MM_Plant> MM_Plant { get; set; }
        public virtual DbSet<MM_Rights> MM_Rights { get; set; }
        public virtual DbSet<MM_Roles> MM_Roles { get; set; }
        public virtual DbSet<MM_Schedule_Type_Master> MM_Schedule_Type_Master { get; set; }
        public virtual DbSet<MM_Shift> MM_Shift { get; set; }
        public virtual DbSet<MM_Shop> MM_Shop { get; set; }
        public virtual DbSet<MM_SpecificationMaster> MM_SpecificationMaster { get; set; }
        public virtual DbSet<MM_Sub_Menus> MM_Sub_Menus { get; set; }
        public virtual DbSet<MM_Track_Sheet> MM_Track_Sheet { get; set; }
        public virtual DbSet<MM_User_Activity_Logs> MM_User_Activity_Logs { get; set; }
        public virtual DbSet<MM_User_Log> MM_User_Log { get; set; }
        public virtual DbSet<MM_User_Roles> MM_User_Roles { get; set; }
        public virtual DbSet<MM_UserActivity_Log> MM_UserActivity_Log { get; set; }
        public virtual DbSet<MM_Vehicle_Audit> MM_Vehicle_Audit { get; set; }
    }
}
